export function limitsFromEnv(env = process.env) {
  const num = (k, d) => (env[k] ? Number(env[k]) : d);
  return {
    MAX_DAILY_ARTICLES: num("AMOGH_MAX_DAILY_ARTICLES", 100),
    GNEWS_MAX_DAILY: num("AMOGH_GNEWS_MAX_DAILY", 50),
    MAX_SUMMARY_CHARS: num("AMOGH_MAX_SUMMARY_CHARS", 200),
    BURST_PERCENT: num("AMOGH_BURST_PERCENT", 20),
    QUOTA_WARN_PCT: num("AMOGH_QUOTA_WARN_PCT", 0.8),
    COOLDOWN_AT_PCT: num("AMOGH_COOLDOWN_AT_PCT", 0.9),
    VIX_THRESHOLD: num("AMOGH_VIX_THRESHOLD", 18),
    COST_SUMMARY_INR: num("AMOGH_COST_SUMMARY_INR", 0.17),
    COST_TRANSLATION_INR: num("AMOGH_COST_TRANSLATION_INR", 0.35),
  };
}